language: php
dist: trusty
php:
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  fast_finish: true

before_script:
  - composer install --dev --prefer-source

script: ./vendor/bin/phpunit --coverage-text